preload = /home/hruon/.config/wallpapers/great_wave_off_kanagawa/cup.jpg
preload = /home/hruon/.config/wallpapers/great_wave_off_kanagawa/wave_pattern.png
preload = /home/hruon/.config/wallpapers/great_wave_off_kanagawa/tall_pattern.png

wallpaper = DP-2,/home/hruon/.config/wallpapers/great_wave_off_kanagawa/cup.jpg
wallpaper = HDMI-A-1,/home/hruon/.config/wallpapers/great_wave_off_kanagawa/wave_pattern.png
wallpaper = HDMI-A-2,/home/hruon/.config/wallpapers/great_wave_off_kanagawa/tall_pattern.png
